/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import conexion.Conectar;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Jared
 */
public class ConsultaYEstadisticas extends javax.swing.JInternalFrame {

    Conectar condb = new Conectar();
    Connection conn = condb.conexion();
    PreparedStatement pst;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form ConsultaYEstadisticas
     */
    public ConsultaYEstadisticas() {
        initComponents();
        Alumnos();
        Cursos();
        Docentes();
        Graficar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_profesores = new javax.swing.JLabel();
        lbl_alumnos = new javax.swing.JLabel();
        lbl_cursos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelGrafica = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Teacher.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Alumnos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Cursos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Docentes");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 20));

        lbl_profesores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_profesores.setText("jLabel8");
        jPanel1.add(lbl_profesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, 20));

        lbl_alumnos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_alumnos.setText("...........");
        jPanel1.add(lbl_alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 40, 20));

        lbl_cursos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_cursos.setText(".................");
        jPanel1.add(lbl_cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Course Assign.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Education.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Consultas y Estadisticas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 25.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 24.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 23(1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Alumnos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Busqueda");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(90, 166, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 110, 30));

        javax.swing.GroupLayout jPanelGraficaLayout = new javax.swing.GroupLayout(jPanelGrafica);
        jPanelGrafica.setLayout(jPanelGraficaLayout);
        jPanelGraficaLayout.setHorizontalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanelGraficaLayout.setVerticalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 360, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Alumnos() {
        try {
            String sql = "SELECT COUNT(*) FROM alumno";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                lbl_alumnos.setText(rs.getString("COUNT(*)"));

            }
        } catch (Exception e) {
        }
    }

    private void Cursos() {
        try {
            String sql = "SELECT COUNT(*) FROM curso";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                lbl_cursos.setText(rs.getString("COUNT(*)"));

            }
        } catch (Exception e) {
        }
    }

    private void Docentes() {
        try {
            String sql = "SELECT COUNT(*) FROM docente";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                lbl_profesores.setText(rs.getString("COUNT(*)"));

            }
        } catch (Exception e) {
        }
    }
    DefaultPieDataset data = new DefaultPieDataset();

    private void Graficar() {

//        JFreeChart barra = null;
//        DefaultCategoryDataset datos;
//        datos = new DefaultCategoryDataset();
        String query = "SELECT COUNT(calificacion) AS Excelencia FROM  toma WHERE calificacion >= 100";
        String qry = "SELECT COUNT(calificacion) AS Regular FROM  toma WHERE calificacion >= 80";
        String qy = "SELECT COUNT(calificacion) AS BAJO FROM  toma WHERE calificacion >= 70";
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);
            Statement sentecnia = conn.createStatement();
            ResultSet resultado = sentecnia.executeQuery(qry);
            Statement snt = conn.createStatement();
            ResultSet rst = snt.executeQuery(qy);
            
            if (rs.next() ) {
                data.setValue("100", Integer.parseInt(rs.getString("Excelencia")));
             
              
            }
             if ( resultado.next()) {
                   data.setValue("80-99", Integer.parseInt(resultado.getString("Regular")));
            }
             if ( rst.next()) {
                  data.setValue("70-79", Integer.parseInt(rst.getString("BAJO")));
            }
            JFreeChart chart = ChartFactory.createPieChart(
                    "Calificaciones Generales", // Título del gráfico
                    data, // DataSet
                    true, // Leyenda
                    true, // ToolTips
                    true);

// Mostrando el gráfico en un jPanel
            this.jPanelGrafica.removeAll();
            this.jPanelGrafica.setLayout(new java.awt.BorderLayout());
            this.jPanelGrafica.add(new ChartPanel(chart)); 
            this.jPanelGrafica.validate();

        } catch (Exception e) {
        }
// Creando el gráfico

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGrafica;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_alumnos;
    private javax.swing.JLabel lbl_cursos;
    private javax.swing.JLabel lbl_profesores;
    // End of variables declaration//GEN-END:variables
}
