package Interfaces;

import conexion.Conectar;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FrmLogin extends javax.swing.JFrame {

    Conectar condb = new Conectar();
    Connection conn = condb.conexion();
    Statement st;
    ResultSet rs;

    public FrmLogin() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarRoles();
        lbl_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contraseña1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcb_perfiles = new javax.swing.JComboBox<>();
        lbl_id = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contraseña1.setText("Usuario");
        getContentPane().add(Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario.setText("Contraseña");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        txt_usuario.setBackground(new java.awt.Color(246, 246, 246));
        txt_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_usuario.setBorder(null);
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 342, 240, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("ESCOLAR");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(90, 166, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INGRESAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 240, 30));

        jLabel4.setText("SELECCIONAR PERFIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jcb_perfiles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONAR--" }));
        jcb_perfiles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_perfilesItemStateChanged(evt);
            }
        });
        jcb_perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_perfilesActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_perfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 272, 240, 30));

        lbl_id.setText("id");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 57, -1));

        txt_password.setBackground(new java.awt.Color(246, 246, 246));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_password.setBorder(null);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 240, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/blue graduation hat(1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("SISTEMA DE GESTION ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 85.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MacBook Pro 14_ - Inicio Sesion.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("SISTEMA DE GESTION ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contraseña.setText("Usuario");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("ESCOLAR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 85.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MacBook Pro 14_ - Inicio Sesion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_perfilesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_perfilesItemStateChanged
        try {
            MostrarIdRoles();
        } catch (SQLException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcb_perfilesItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Logueo(txt_usuario.getText(), txt_password.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcb_perfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_perfilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_perfilesActionPerformed

    

    public void MostrarRoles() throws SQLException {
        st = conn.createStatement();
        try {
            String sql = "SELECT descripcion FROM rol";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                jcb_perfiles.addItem(rs.getString("descripcion"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar " + e.getMessage());
        }

    }

    public void MostrarIdRoles() throws SQLException {
        st = conn.createStatement();
        try {
            String sql = "SELECT id FROM rol WHERE descripcion ='" + jcb_perfiles.getSelectedItem().toString() + "'";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                lbl_id.setText(rs.getString("id"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar " + e.getMessage());
        }

    }

    public void Logueo(String usuario, String password) {
        try {

            String sql = "SELECT * FROM usuarios WHERE usuario='" + usuario + "' and password='" + password + "'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Bienvenido(a)");
                switch (jcb_perfiles.getSelectedIndex()) {
                    case 1 -> {
                        MenuAdministrador admin = new MenuAdministrador();
                        admin.setVisible(true);
                        admin.lbl_usuario.setText(rs.getString("usuario"));                        
                        this.dispose();
                    }
                    case 2 -> {
                    }
                    case 3 -> {
                       MenuControlEscolar encargado = new MenuControlEscolar();
                        encargado.setVisible(true);
                        this.dispose();
                    }
                    case 4 -> {
                    }
                    default -> {
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario y contraseña incorrectos", "Datos Incorrectos", JOptionPane.ERROR_MESSAGE);
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error de conexion " + e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Contraseña1;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcb_perfiles;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
