/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.itextpdf.text.Chunk;
import conexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/**
 *
 * @author Jared
 */
public class MenuAlumnos extends javax.swing.JFrame {

    DefaultTableModel details;

    Conectar condb = new Conectar();
    Connection conn = condb.conexion();

    PreparedStatement pst;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form MenuAlumnos
     */
    public MenuAlumnos() {
        initComponents();
        this.setLocationRelativeTo(null);

        lbl_idsemestre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_calificacion = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_promedio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblpaterno = new javax.swing.JLabel();
        lblmaterno = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_idalumno = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_idsemestre = new javax.swing.JLabel();
        lbl_semestre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_turno = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_grupo = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_calificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_calificacion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 500, 140));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Calificaciones");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Historial ");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Academico");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jButton1.setBackground(new java.awt.Color(90, 166, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generar ");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 570, 540));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Promedio Global");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lbl_promedio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_promedio.setText(".");
        jPanel4.add(lbl_promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 230, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MacBook Pro 14_ - Inicio Sesion.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 910, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lbltelefono.setText(" ");
        jPanel1.add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 110, -1));

        jLabel6.setText("Apellido Paterno:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setText("Apellido Materno:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lblnombre.setText(" ");
        jPanel1.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, -1));

        lblpaterno.setText(" ");
        jPanel1.add(lblpaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, -1));

        lblmaterno.setText(" ");
        jPanel1.add(lblmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, -1));

        jButton3.setBackground(new java.awt.Color(90, 166, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cerrar Sesion");
        jButton3.setBorderPainted(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/girl taking notes.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 200));

        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("ID alumno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel1.add(lbl_idalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, 20));

        jLabel11.setText("Semestre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPanel1.add(lbl_idsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 30, 20));
        jPanel1.add(lbl_semestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 120, 20));

        jLabel12.setText("Turno");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        jPanel1.add(lbl_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, 20));

        jLabel13.setText("Gupo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        jPanel1.add(lbl_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 120, 20));
        jPanel1.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("ESTUDIANTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "¿Estás seguro de cerrar tu sesión?", "Confirmación", 0);
        if (s == 0) {
            this.dispose();
            JOptionPane.showMessageDialog(null, "!!Hasta pronto!!");
            FrmLogin login;
            try {
                login = new FrmLogin();
                login.setVisible(true);
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Document kardex = new Document(PageSize.A4.rotate());
        String d=lblnombre.getText()+lblpaterno.getText()+lblmaterno.getText();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(kardex, new FileOutputStream(ruta + "/OneDrive/Desktop/SISGE/SISGE/Reportes/ReporteHistorial/Kardex"+d+".pdf")).setInitialLeading(20);
            kardex.open();

            PdfPTable tabla = new PdfPTable(3);
            tabla.addCell("Semestre");
            tabla.addCell("Asignatura");
            tabla.addCell("Calificacion");
            try {
                String sql = "select c.semestre as semestre, c.nombre as curso, ifnull(tm.calificacion,'') as calificacion\n"
                + "from curso c\n"
                + "left outer join toma tm on c.id_curso=tm.id_curso\n"
                + "and id_alumno='"+Integer.parseInt(lbl_idalumno.getText())+"'\n"
                + "order by semestre,curso ASC";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                    } while (rs.next());
                    Font f = new Font();
                    f.setStyle(Font.BOLD);
                    f.setSize(15);
                    Paragraph p = new Paragraph();
                    p.setFont(f);
                    p.add("HISTORIAL ACADÉMICO");
                    p.setAlignment(Element.ALIGN_CENTER);
                    kardex.add(p);
                    kardex.add(Chunk.NEWLINE);

                    try {
                        String query = "SELECT paterno, materno, nombre from alumno where id_alumno='"
                        + Integer.parseInt(lbl_idalumno.getText()) + "'";
                        st = conn.createStatement();
                        rs = st.executeQuery(query);

                        if (rs.next()) {
                            String cs = rs.getString("paterno") + " " + rs.getString("materno") + " " + rs.getString("nombre");

                            String datos = "ALUMNO: " + cs.toUpperCase();
                            Font f2 = new Font();
                            f2.setStyle(Font.BOLD);
                            f2.setSize(15);
                            Paragraph p2 = new Paragraph();
                            p2.setFont(f2);
                            p2.add(datos);
                            p2.setAlignment(Element.ALIGN_LEFT);
                            kardex.add(p2);
                            kardex.add(Chunk.NEWLINE);
                        }

                    } catch (Exception e) {
                    }

                    try {
                        String query = "select c.descripcion as carrera from carrera c, inscripcion i, alumno a "
                        + "where i.carrera=c.id_carrera and a.id_alumno=i.id_alumno and i.id_alumno='" + Integer.parseInt(lbl_idalumno.getText()) + "'";
                        st = conn.createStatement();
                        rs = st.executeQuery(query);

                        if (rs.next()) {
                            String cs = rs.getString("carrera");

                            String promedio = "CARRERA: " + cs;
                            Font f2 = new Font();
                            f2.setStyle(Font.BOLD);
                            f2.setSize(15);
                            Paragraph p2 = new Paragraph();
                            p2.setFont(f2);
                            p2.add(promedio);
                            p2.setAlignment(Element.ALIGN_LEFT);
                            kardex.add(p2);
                            kardex.add(Chunk.NEWLINE);
                        }

                    } catch (Exception e) {
                    }

                    try {
                        String query = "SELECT avg (tm.calificacion) as promedio\n"
                        + "FROM toma tm, curso c, alumno al, grupos gp, turno trn , semestre sm, docente d\n"
                        + "WHERE tm.id_curso = c.id_curso\n"
                        + "AND tm.id_alumno = al.id_alumno\n"
                        + "AND tm.id_grupo = gp.id_grupo\n"
                        + "AND tm.id_turno = trn.id_turno\n"
                        + "AND tm.id_semestre = sm.id_semestre\n"
                        + "AND tm.id_docente = d.id_docente\n"
                        + "and al.id_alumno='" + Integer.parseInt(lbl_idalumno.getText()) + "'\n"
                        + "ORDER BY id_toma ASC";
                        st = conn.createStatement();
                        rs = st.executeQuery(query);

                        if (rs.next()) {
                            String cs = rs.getString("promedio");

                            String promedio = "Promedio Global " + cs;
                            Font f2 = new Font();
                            f2.setStyle(Font.BOLD);
                            f2.setSize(15);
                            Paragraph p2 = new Paragraph();
                            p2.setFont(f2);
                            p2.add(promedio);
                            p2.setAlignment(Element.ALIGN_RIGHT);
                            kardex.add(p2);
                            kardex.add(Chunk.NEWLINE);
                        }

                    } catch (DocumentException | NumberFormatException | SQLException e) {
                    }
                    kardex.add(tabla);
                }
                kardex.close();
                JOptionPane.showMessageDialog(null, "Documento generado exitosamente");
            } catch (DocumentException | HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al generar" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al generar" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAlumnos().setVisible(true);
            }
        });
    }

    public void MostrarCalificaciones() {
        details = new DefaultTableModel();
        details.addColumn("Asignatura");
        details.addColumn("Semestre");
        details.addColumn("Calificacion");
        details.addColumn("Docente");
        tbl_calificacion.setModel(details);

        Object[] vector = new String[4];
        String sql = "SELECT c.nombre, tm.id_semestre, tm.calificacion, d.nombre\n"
                + "FROM toma tm, curso c, alumno al, grupos gp, turno trn , semestre sm, docente d\n"
                + "WHERE tm.id_curso = c.id_curso\n"
                + "AND tm.id_alumno = al.id_alumno\n"
                + "AND tm.id_grupo = gp.id_grupo\n"
                + "AND tm.id_turno = trn.id_turno\n"
                + "AND tm.id_semestre = sm.id_semestre\n"
                + "AND tm.id_docente = d.id_docente\n"
                + "and al.id_alumno='" + Integer.parseInt(lbl_idalumno.getText()) + "'\n"
                + "ORDER BY id_toma ASC";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                vector[0] = rs.getString(1);
                vector[1] = rs.getString(2);
                vector[2] = rs.getString(3);
                vector[3] = rs.getString(4);
                details.addRow(vector);
            }
            tbl_calificacion.setModel(details);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void MostrarSemestre() {
        String sql = "select i.id_alumno as id, g.grupo as grupo, s.descripcion as semestre, trn.descripcion as turno"
                + " from alumno a, inscripcion i, grupos g, semestre s, turno trn"
                + " where i.id_alumno='" + Integer.parseInt(lbl_idalumno.getText()) + "' and i.id_alumno=a.id_alumno and i.grupo=g.id_grupo and g.semestre=s.id_semestre and i.turno=trn.id_turno";
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lbl_idsemestre.setText(rs.getString("id"));
                lbl_semestre.setText(rs.getString("semestre"));
                lbl_turno.setText(rs.getString("turno"));
                lbl_grupo.setText(rs.getString("grupo"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void MostrarPromedio() {
        String sql = "SELECT avg (tm.calificacion) as promedio\n"
                + "FROM toma tm, curso c, alumno al, grupos gp, turno trn , semestre sm, docente d\n"
                + "WHERE tm.id_curso = c.id_curso\n"
                + "AND tm.id_alumno = al.id_alumno\n"
                + "AND tm.id_grupo = gp.id_grupo\n"
                + "AND tm.id_turno = trn.id_turno\n"
                + "AND tm.id_semestre = sm.id_semestre\n"
                + "AND tm.id_docente = d.id_docente\n"
                + "and al.id_alumno='" + Integer.parseInt(lbl_idalumno.getText()) + "'\n"
                + "ORDER BY id_toma ASC";
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lbl_promedio.setText(rs.getString("promedio"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_grupo;
    public javax.swing.JLabel lbl_idalumno;
    private javax.swing.JLabel lbl_idsemestre;
    private javax.swing.JLabel lbl_promedio;
    private javax.swing.JLabel lbl_semestre;
    private javax.swing.JLabel lbl_turno;
    public javax.swing.JLabel lbl_user;
    public javax.swing.JLabel lblmaterno;
    public javax.swing.JLabel lblnombre;
    public javax.swing.JLabel lblpaterno;
    public javax.swing.JLabel lbltelefono;
    private javax.swing.JTable tbl_calificacion;
    // End of variables declaration//GEN-END:variables
}
