/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import conexion.Conectar;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jared
 */
public class ModificarCalificacion extends javax.swing.JFrame {
    Conectar con = new Conectar();
    Connection conn = con.conexion();
    /**
     * Creates new form ModificarCalificacion
     */
    public ModificarCalificacion() {
        initComponents();
          this.setLocationRelativeTo(null);
          txtid.setEnabled(false);
          txtgrupo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcalificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCancell = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtgrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ACTUALIZAR CALIFICACION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtcalificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtcalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 30));

        jLabel2.setText("Grupo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btnCancell.setBackground(new java.awt.Color(255, 51, 51));
        btnCancell.setForeground(new java.awt.Color(255, 255, 255));
        btnCancell.setText("Cancelar");
        btnCancell.setBorderPainted(false);
        btnCancell.setDefaultCapable(false);
        btnCancell.setFocusPainted(false);
        btnCancell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancell, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, -1));

        btnmodif.setBackground(new java.awt.Color(90, 166, 255));
        btnmodif.setForeground(new java.awt.Color(255, 255, 255));
        btnmodif.setText("Actualizar");
        btnmodif.setBorderPainted(false);
        btnmodif.setDefaultCapable(false);
        btnmodif.setFocusPainted(false);
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, -1));

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, -1));

        jLabel3.setText("Calificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtgrupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtgrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        // TODO add your handling code here:
            try {
            modificar();
        } catch (SQLException ex) {
            Logger.getLogger(ModificarAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnCancellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellActionPerformed
        // TODO add your handling code here:
           MenuDocentes docentes  = new MenuDocentes();
           docentes.setVisible(true);
    }//GEN-LAST:event_btnCancellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCalificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarCalificacion().setVisible(true);
            }
        });
    }
    public void Recibir(String calificacion, String id, String grupo){
        txtcalificacion.setText(calificacion);
        txtid.setText(id);
        txtgrupo.setText(grupo);
    }

    private void modificar() throws SQLException{
        MenuDocentes docentes  = new MenuDocentes();
        FrmAltaCalificaciones panel = new FrmAltaCalificaciones();
        String calificacion = txtcalificacion.getText();
                String id = txtid.getText();
        try {
             PreparedStatement pst = conn.prepareStatement("UPDATE toma SET calificacion='" + calificacion + "'WHERE id_calificacion='"+ id + "'");
                         int s = JOptionPane.showConfirmDialog(null, "¿Estás seguro de modificar el registro?", "CONFIRMACIÓN", 0);
                         if (s == 0) {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Datos modificados correctamente"); 
                panel.mostrardatos();
                panel.setVisible(true);                
                this.dispose();                
            }
        } catch (HeadlessException | SQLException e) {
             JOptionPane.showMessageDialog(null, "Ha ocurrido un error " + e, "Error inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancell;
    private javax.swing.JButton btnmodif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcalificacion;
    private javax.swing.JTextField txtgrupo;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
